set(CMAKE_SYSTEM_NAME "DOS")
set(CMAKE_SYSTEM_PROCESSOR "I86")

set(WATCOM_ROOT "$ENV{WATCOM}" CACHE PATH "Root of WatCom compiler")

if(NOT WATCOM_ROOT)
    message(FATAL_ERROR "WATCOM environment variable not set (saved in WATCOM_ROOT CMake variable)")
endif()

find_program(CMAKE_C_COMPILER NAMES wcl)
find_program(CMAKE_CXX_COMPILER NAMES wcl)

if(NOT CMAKE_C_COMPILER OR NOT CMAKE_CXX_COMPILER)
    message(FATAL_ERROR "Could not find wcl, make sure the directory containing wcl is added to your PATH")
endif()

list(APPEND CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${WATCOM_ROOT}/h")
list(APPEND CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "${WATCOM_ROOT}/h")
list(APPEND CMAKE_SYSTEM_INCLUDE_PATH "${WATCOM_ROOT}/h")

list(APPEND CMAKE_SYSTEM_LIBRARY_PATH "${WATCOM_ROOT}/lib286;${WATCOM_ROOT}/lib286/dos")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)